### ISSUE TITLE
ArgumentComponent and ArgumentRelation are missing

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro-argumentation#9] opened 2016-06-22 12:28 UTC
This project doesn't compile for me because the `ArgumentComponent` and `ArgumentRelation` classes are missing.  Did someone forget to check them in?

**Comment by habernal** [comment] 2016-06-22 12:36
Try `mvn clean` and `mvn compile`. These classes are generated from `dkpro-argumentation/de.tudarmstadt.ukp.dkpro.argumentation.types/src/main/resources/desc/types/ArgumentationTypeSystem.xml` by maven compile plugin.

**Comment by logological** [comment] 2016-06-22 12:46
OK, doing that from the command line solved it.  Strange that Eclipse wasn't able to compile the classes when I first imported the project.

**Comment by habernal** [comment] 2016-06-22 12:49
Closing as not a bug; Eclipse-related.

**Closed as completed by habernal** 2016-06-22 12:49 UTC
Labels: invalid

**Comment by reckart** [comment] 2016-06-22 12:52
Assuming you have a modern eclipse and modern m2e installed, the stuff should be automatically generated on checkout/build/rebuild.

**Comment by logological** [comment] 2016-06-22 13:20
I'm running Mars.2 (Eclipse 4.5.2) with version 0.15.0.201207090124 of the m2e connector.  I tried deleting the project from Eclipse, doing `mvn clean` from the command line, and then reimporting the project into Eclipse.  This time it built correctly.  So looks like I had a transient problem with Eclipse.

**Comment by reckart** [comment] 2016-06-22 13:30
m2e  0.15.0.201207090124 sounds old. I have 1.7.0.20160603-1933 installed.

Update site: http://download.eclipse.org/technology/m2e/milestones/1.7/
